#!/usr/bin/perl -T
#
# Name: cnames
# Creator: Guy Edwards
# Created: 2008-10-10
# Description:  Page to support creation of DNS records from frodo names
#
# $Id: cnames 3539 2012-02-10 16:01:31Z guy $
# $LastChangedBy: guy $
# $LastChangedDate: 2012-02-10 16:01:31 +0000 (Fri, 10 Feb 2012) $
# $LastChangedRevision: 3539 $
# $uid: iWiiJ6Q6CPbNQq8qGX7BdqefQaUWSOyzPE4zNZT7Dt8xX $
#

use warnings FATAL => 'all';
use strict;

use CGI;
use Config::Tiny;
use DBI;
use DBD::Pg;
use Template;

use Inventory qw(dbconnect populate_query_fields acl_checker);
use Inventory::Cnames qw(create_cnames get_cnames_info edit_cnames);

my $BASEURL = CGI::url( -base => 1 );
my $HOSTNAME = $BASEURL;

# remove everything from the first . onwards
$HOSTNAME =~ s/\..*$//gx;

# remove everything from the start to the last /
$HOSTNAME =~ s/^.*\///gx;

my $CONFIG      = Config::Tiny->new();
my $CONFIG_FILE = "/srv/www/$HOSTNAME/lib/inventory.ini";
$CONFIG = Config::Tiny->read("$CONFIG_FILE");

my $dbhost      = $CONFIG->{'database'}->{db_host};
my $dbname      = $CONFIG->{'database'}->{db_name};
my $dbuser      = $CONFIG->{'database'}->{db_user};
my $dbpass      = $CONFIG->{'database'}->{db_pass};
my $dbh         = Inventory::dbconnect( $dbname, $dbuser, $dbhost, $dbpass );
my $valid_users = $CONFIG->{'general'}->{allowed_users};
my $htmltemplatepath = $CONFIG->{'locations'}->{tt_dir};

#############################################################################
#                                     main                                  #
#############################################################################

my $q = CGI->new();
print $q->header();

# this just loads the default site settings
my $tt = Template->new( { INCLUDE_PATH => $htmltemplatepath, } );

# print the stock header (banner and title)
$tt->process(
    'inventory_header.tt',
    {
        pagetitle  => 'DNS records',
        baseurl    => $BASEURL,
        extramenu  => 'inventory',
        javascript => 'on',
    }
);

# invalid users get no further than the next line
Inventory::acl_checker( $tt, $valid_users );

# I differenciate between get and post, not everyone agrees with this but
# there is an RFC2616 that suggests that we should. I do so for behaviour not
# security reasons.
#
my %gets = Inventory::populate_query_fields();    # not strictly a get field
of course my %POSTS;
if ( $ENV{REQUEST_METHOD} eq 'POST' ) {
    %POSTS = $q->Vars;
}

my ( $edit, $makehost_id, $delete );

# the page is being called to create a cname for a specific host
if ( exists $gets{'host_id'} ) {
    $makehost_id = $gets{'host_id'};
}

if ( $gets{'cname_id'} && $gets{'cname_id'} =~ m/^[\d]+$/x ) {
    if ( exists $gets{'action'} and $gets{'action'} eq 'edit' ) {
        $edit = $gets{'cname_id'};
    }
    elsif ( exists $gets{'action'} and $gets{'action'} eq 'delete' ) {
        $delete = $gets{'cname_id'};
    }
}

my @message_store;    # communicate success or failure, sink or swim

# are we taking action?
if ( exists $POSTS{'action'} ) {
    if ( $POSTS{'action'} eq 'delete' ) {
        @message_store =
          Inventory::Cnames::delete_cname( $dbh, $POSTS{'cname_id'} );
    }
    if ( $POSTS{'action'} eq 'edit' ) {
        @message_store = Inventory::Cnames::edit_cnames( $dbh, \%POSTS );
    }
    if ( $POSTS{'action'} eq 'create' ) {
        @message_store = Inventory::Cnames::create_cnames( $dbh, \%POSTS );
    }
}

# list all the cnames (array of hashes)
my @cnames = Inventory::Cnames::get_cnames_info($dbh);

# list all the hosts (array of hashes)
my @hosts = Inventory::Hosts::get_hosts_info($dbh);

$tt->process(
    'inventory_cnames.tt',
    {
        cnames        => \@cnames,
        message_store => \@message_store,
        edit          => $edit,
        delete        => $delete,
        hosts         => \@hosts,
        makehost_id   => $makehost_id,
    }
);
$tt->process('stdfoot.tt');

__END__

=head1 NAME
cnames

=head1 VERSION

This documentation refers to  version 

=head1 USAGE

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 DESCRIPTION

It was never intended that the inventory would be a dns configuration tool

Sadly at the very end of the inventory implementation it became apparent 
that the DNS used the exiting database to generate the frodo zones. 
The Inventory was designed to rely upon DNS. This page was designed to 
break the cuircular dependancy but it will never be anything other than
an afterthought

=head1 DIAGNOSTICS

error messages should be reported to the user via the web interface

=head1 CONFIGURATION

via /srv/www/$HOSTNAME/lib/inventory.ini

=head1 DEPENDENCIES

=head1 INCOMPATIBILITIES

none known

=head1 BUGS AND LIMITATIONS

Report any found to <hostmaster@ox.ac.uk>

=head1 AUTHOR

Guy Edwards, maintained by <hostmaster@ox.ac.uk>

=head1 LICENSE AND COPYRIGHT



(c) University of Oxford
