#!/usr/bin/perl -T
#
# Name: frodo
# Creator: Guy Edwards
# Created: 2008-09-10
# Description: Frodo Project Overview page
#
# $Id: frodo 3538 2012-02-10 15:39:37Z guy $
# $LastChangedBy: guy $
# $LastChangedDate: 2012-02-10 15:39:37 +0000 (Fri, 10 Feb 2012) $
# $LastChangedRevision: 3538 $
# $uid: PxPLvXfZWSGS2DA_sR48fxAchSL9i5hKahAptc9uq1PjL $
#
use warnings FATAL => 'all';
use strict;

use CGI;
use Config::Tiny;
use DBI;
use DBD::Pg;
use Template;

use Inventory qw(dbconnect populate_query_fields acl_checker);
use Inventory::Ups qw(get_links_info);
use Inventory::Frodos qw(ordered_hash_frodos);

my $BASEURL = CGI::url( -base => 1 );
my $HOSTNAME = $BASEURL;

# remove everything from the first . onwards
$HOSTNAME =~ s/\..*$//gx;

# remove everything from the start to the last /
$HOSTNAME =~ s/^.*\///gx;

my $CONFIG      = Config::Tiny->new();
my $CONFIG_FILE = "/srv/www/$HOSTNAME/lib/inventory.ini";
$CONFIG = Config::Tiny->read("$CONFIG_FILE");

my $dbhost           = $CONFIG->{'database'}->{db_host};
my $dbname           = $CONFIG->{'database'}->{db_name};
my $dbuser           = $CONFIG->{'database'}->{db_user};
my $dbpass           = $CONFIG->{'database'}->{db_pass};
my $dbh              = dbconnect( $dbname, $dbuser, $dbhost, $dbpass );
my $valid_users      = $CONFIG->{'general'}->{allowed_users};
my $htmltemplatepath = $CONFIG->{'locations'}->{tt_dir};

#############################################################################
#                                     main                                  #
#############################################################################

my $q = CGI->new();
print $q->header();

# this just loads the default site settings
my $tt = Template->new( { INCLUDE_PATH => $htmltemplatepath, } );

# print the stock header (banner and title)
$tt->process(
    'inventory_header.tt',
    {
        pagetitle  => 'Frodo Overview',
        baseurl    => $BASEURL,
        extramenu  => 'inventory',
        javascript => 'on',
    }
);

# I differenciate between get and post, not everyone agrees with this but
# there is an RFC2616 that suggests that we should. I do so for behaviour not
# security reasons.
my %gets =
  Inventory::populate_query_fields();    # not strictly a get field of course
my $orderby;
if ( !exists $gets{'orderby'} || $gets{'orderby'} =~ m/\W/x ) {
    $orderby = 'host_name';
}
else {
    $orderby = $gets{'orderby'};
}

# invalid users get no further than the next line
Inventory::acl_checker( $tt, $valid_users );

# all the frodos
my %frodos = %{ ordered_hash_frodos( $dbh, $orderby ) };

# all the ups joined to hosts
my @links = Inventory::Ups::get_links_info($dbh);

$tt->process(
    'inventory_frodo.tt',
    {
        frodos => \%frodos,
        links  => \@links,
    }
);
$tt->process('stdfoot.tt');

__END__

=head1 NAME
frodo

=head1 VERSION

This documentation refers to  version 

=head1 USAGE

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 DESCRIPTION

Creates the frodo overview page for the inventory, with links to various tools

Note that this is subtly different to the evil-frodo page. It may be possible to combine the two sets of code at some point.

=head1 DIAGNOSTICS

error messages

=head1 CONFIGURATION

Configuration files used?

=head1 DEPENDENCIES

=head1 INCOMPATIBILITIES

none known

=head1 BUGS AND LIMITATIONS

Report any found to <hostmaster@ox.ac.uk>

=head1 AUTHOR

Guy Edwards, maintained by <hostmaster@ox.ac.uk>

=head1 LICENSE AND COPYRIGHT



(c) University of Oxford
