#!/usr/bin/perl -T
#
# Name: hostgroups
# Creator: Guy Edwards
# Created: 2008-07-28
# Description: Hostgroups administration page for the inventory application
#
# $Id: hostgroups 3538 2012-02-10 15:39:37Z guy $
# $LastChangedBy: guy $
# $LastChangedDate: 2012-02-10 15:39:37 +0000 (Fri, 10 Feb 2012) $
# $LastChangedRevision: 3538 $
# $uid: MgaQaSEQg8xGVweT71j0mLv17aUzDmPWRx3Yhx6rnGEgq $
#

use warnings FATAL => 'all';
use strict;

use CGI;
use Config::Tiny;
use DBI;
use DBD::Pg;
use Template;

use Inventory qw(dbconnect populate_query_fields acl_checker is_superuser);
use Inventory::Hostgroups
  qw(create_hostgroups edit_hostgroups get_hostgroups_info);
use Inventory::Memberships qw(count_memberships);

my $BASEURL = CGI::url( -base => 1 );
my $HOSTNAME = $BASEURL;

# remove everything from the first . onwards
$HOSTNAME =~ s/\..*$//gx;

# remove everything from the start to the last /
$HOSTNAME =~ s/^.*\///gx;

my $CONFIG      = Config::Tiny->new();
my $CONFIG_FILE = "/srv/www/$HOSTNAME/lib/inventory.ini";
$CONFIG = Config::Tiny->read("$CONFIG_FILE");

my $dbhost           = $CONFIG->{'database'}->{db_host};
my $dbname           = $CONFIG->{'database'}->{db_name};
my $dbuser           = $CONFIG->{'database'}->{db_user};
my $dbpass           = $CONFIG->{'database'}->{db_pass};
my $dbh              = dbconnect( $dbname, $dbuser, $dbhost, $dbpass );
my $valid_users      = $CONFIG->{'general'}->{allowed_users};
my $htmltemplatepath = $CONFIG->{'locations'}->{tt_dir};

#############################################################################
#                                     main                                  #
#############################################################################

my $q = CGI->new();
print $q->header();

# this just loads the default site settings
my $tt = Template->new( { INCLUDE_PATH => $htmltemplatepath, } );

# print the stock header (banner and title)
$tt->process(
    'inventory_header.tt',
    {
        pagetitle  => 'Hostgroups',
        baseurl    => $BASEURL,
        extramenu  => 'inventory',
        javascript => 'on',
    }
);

# invalid users get no further than the next line
Inventory::acl_checker( $tt, $valid_users );

# I differenciate between get and post, not everyone agrees with this but
# there is an RFC2616 that suggests that we should. I do so for behaviour not
# security reasons.
my %gets = populate_query_fields();    # not strictly a get field of course
my %POSTS;
if ( $ENV{REQUEST_METHOD} eq 'POST' ) {
    %POSTS = $q->Vars;
}

my $edit;
if ( $gets{'hostgroup_id'} && $gets{'hostgroup_id'} !~ m/\D/x ) {
    $edit = $gets{'hostgroup_id'};
}

my %message;    # communicate success or failure, sink or swim

# are we editing an existing entry?
if ( $POSTS{'hostgroup_id'} ) {
    %message = %{ Inventory::Hostgroups::edit_hostgroups( $dbh, \%POSTS ) };
}
elsif ( $POSTS{'hostgroup_name'} ) {

    # are we creating a new entry?
    %message = %{ Inventory::Hostgroups::create_hostgroups( $dbh, \%POSTS ) };
}

# list all the hostgroups (array of hashes)
my @hostgroups =
  Inventory::Hostgroups::get_hostgroups_info( $dbh, '', $gets{'orderby'},
    $gets{'direction'} );

# get a count per hostgroup
my %group_summary =
  %{ Inventory::Memberships::count_memberships( $dbh, 'group' ) };
my %host_summary =
  %{ Inventory::Memberships::count_memberships( $dbh, 'host' ) };

$tt->process(
    'inventory_hostgroups.tt',
    {
        hostgroups    => \@hostgroups,
        message       => \%message,
        edit          => $edit,
        host_summary  => \%host_summary,
        group_summary => \%group_summary,
    }
);
$tt->process('stdfoot.tt');

__END__

=head1 NAME
hostgroups

=head1 VERSION

This documentation refers to  version 

=head1 USAGE

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 DESCRIPTION

=head1 DIAGNOSTICS

error messages

=head1 CONFIGURATION

Configuration files used?

=head1 DEPENDENCIES

=head1 INCOMPATIBILITIES

none known

=head1 BUGS AND LIMITATIONS

Report any found to <hostmaster@ox.ac.uk>

=head1 AUTHOR


, maintained by <hostmaster@ox.ac.uk>

=head1 LICENSE AND COPYRIGHT



(c) University of Oxford
