=head1 INTRODUCTION

This is a network device inventory that was written in 2007 and used
internally to university network support team as a central data source and to
feed a network monitoring system.

It was approved for release as open source code on the 10th February 2012

At the time of public release the code is in the process of being
'publicified' so may make references to private/in house systems and terms or
be in a non working state where parts have been rmeoved. 

It's intended to fix this as soon as possible, a working demonstration site is
currently being configured.

=head1 INSTALLATION

The major steps currently involve:

=over 4

=item Make a database using the SQL in conf/*.sql

=item Copy the perl modules into place on the webserver

=item Copy the perl scripts, templates, images and stylesheets into the wbeservers directory

=item Configure apache

=item Configure the sites .ini file 

=item Test

=back

The INSTALL file contains a more complete guide to the current install process
(warts and all) but it's intended that this process will be significantly
improved shortly.


=head2 Dependencies

Currently uses

Carp,
CGI,
Config,
DateTime,
DBD,
DBI,
Digest,
File,
Net,
NetAddr,
Regexp,
Socket,
Template,
URI


=head1 FUTURE WORK

The todo file contains the full future roadmap in terms of improvements and
new features.

=head1 COPYRIGHT AND LICENCE

Network Device Inventory - keep a database of devices to feed other systems
(such as monitoring software). Copyright 2007 University of Oxford

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
Street, Fifth Floor, Boston, MA 02110-1301 USA.

The University of Oxford agrees to the release under the GPL of in the program
`Inventory' written by Guy Edwards as agreed by Dr. Stuart Lee, Director of
Oxford University Computer Services.

Oliver Gorwits, who in 2008 contributed sections of the hostgroups programming
also agreed to the code release under the GPL.
