#!/usr/bin/perl -T
#
# Name: sshkeys
# Creator: Guy Edwards
# Created: 2008-07-28
# Description: unknown
# Sshkeys administration page for the inventory application
#
# $Id: sshkeys 3539 2012-02-10 16:01:31Z guy $
# $LastChangedBy: guy $
# $LastChangedDate: 2012-02-10 16:01:31 +0000 (Fri, 10 Feb 2012) $
# $LastChangedRevision: 3539 $
# $uid: 1W20hg_HdKTeRbgGPqYPcPFBUC9jhx3o13jBN4Her1u1m $
#

use warnings FATAL => 'all';
use strict;

use CGI;
use Template;
use Config::Tiny;
use DBI;
use DBD::Pg;

use Inventory qw(dbconnect populate_query_fields acl_checker);
use Inventory::Sshkeys qw(edit_sshkeys create_sshkeys get_sshkeys_info);
use Inventory::Hosts qw(get_hosts_info);

my $BASEURL = CGI::url( -base => 1 );
my $HOSTNAME = $BASEURL;

# remove everything from the first . onwards
$HOSTNAME =~ s/\..*$//gx;

# remove everything from the start to the last /
$HOSTNAME =~ s/^.*\///gx;

my $CONFIG      = Config::Tiny->new();
my $CONFIG_FILE = "/srv/www/$HOSTNAME/lib/inventory.ini";
$CONFIG = Config::Tiny->read("$CONFIG_FILE");

my $dbhost           = $CONFIG->{'database'}->{db_host};
my $dbname           = $CONFIG->{'database'}->{db_name};
my $dbuser           = $CONFIG->{'database'}->{db_user};
my $dbpass           = $CONFIG->{'database'}->{db_pass};
my $dbh              = dbconnect( $dbname, $dbuser, $dbhost, $dbpass );
my $valid_users      = $CONFIG->{'general'}->{allowed_users};
my $htmltemplatepath = $CONFIG->{'locations'}->{tt_dir};

#############################################################################
#                                     main                                  #
#############################################################################

my $q = CGI->new();
print $q->header();

# this just loads the default site settings
my $tt = Template->new( { INCLUDE_PATH => $htmltemplatepath, } );

# print the stock header (banner and title)
$tt->process(
    'inventory_header.tt',
    {
        pagetitle  => 'SSH Key Fingerprints',
        baseurl    => $BASEURL,
        extramenu  => 'inventory',
        javascript => 'on',
    }
);

# invalid users get no further than the next line
Inventory::acl_checker( $tt, $valid_users );

# I differenciate between get and post, not everyone agrees with this but
# there is an RFC2616 that suggests that we should. I do so for behaviour not
# security reasons.
my %gets =
  Inventory::populate_query_fields();    # not strictly a get field of course
my %POSTS;
if ( $ENV{REQUEST_METHOD} eq 'POST' ) {
    %POSTS = $q->Vars;
}

my ( $edit, $delete );
if ( $gets{'sshkey_id'} && $gets{'sshkey_id'} =~ m/^[\d]+$/x ) {
    if ( exists $gets{'action'} and $gets{'action'} eq 'delete' ) {
        $delete = $gets{'sshkey_id'};
    }
    else {
        $edit = $gets{'sshkey_id'};
    }
}

my %message;    # communicate success or failure, sink or swim

# are we editing/deleting an existing entry?
if ( exists $POSTS{'action'} ) {
    if ( $POSTS{'action'} eq 'delete' ) {
        %message =
          %{ Inventory::Sshkeys::delete_sshkeys( $dbh, $POSTS{'sshkey_id'} ) };
    }
    elsif ( $POSTS{'action'} eq 'edit' ) {
        %message = %{ Inventory::Sshkeys::edit_sshkeys( $dbh, \%POSTS ) };
    }
    elsif ( $POSTS{'action'} eq 'create' ) {
        %message = %{ Inventory::Sshkeys::create_sshkeys( $dbh, \%POSTS ) };
    }
}

# list all the sshkeys (array of hashes)
my @sshkeys = Inventory::Sshkeys::get_sshkeys_info($dbh);

# list all the hosts (array of hashes)
my @hosts = Inventory::Hosts::get_hosts_info($dbh);

# host_id is so that a host without an sshkey can quickly have one added. E.g. on
# the information overview for the host there is a link to 'create an ssh key
# for this host' and selecting that link loads this page with the correct host
# already selected in the new sshkey form.

$tt->process(
    'inventory_sshkeys.tt',
    {
        sshkeys => \@sshkeys,
        message => \%message,
        edit    => $edit,
        delete  => $delete,
        hosts   => \@hosts,
        host_id => $gets{'host_id'},
    }
);
$tt->process( 'stdfoot.tt', {} );

__END__

=head1 NAME

=head1 VERSION

This documentation refers to  version 

=head1 USAGE

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 DESCRIPTION

=head1 DIAGNOSTICS

error messages

=head1 CONFIGURATION AND ENVIRONMENT

Configuration files used?

=head1 DEPENDENCIES

=head1 INCOMPATIBILITIES

none known

=head1 BUGS AND LIMITATIONS

Report any found to <hostmaster@ox.ac.uk>

=head1 AUTHOR


, maintained by <hostmaster@ox.ac.uk>

=head1 LICENSE AND COPYRIGHT



(c) University of Oxford
