=pod

=head1 User Interface

=over 4

=item Client side input validation for the quickdevice page to help give people
an immediate alert if they are typing the frodo- name instead of the
human-friendly name.
 
=item Visual clues to show the user which fields are optional/essential on the
quickdevice page.

=item On the quickdevice page, visual clues highlight required empty fields

=item Not all pages have a delete option - hardware shouldn't be
deleted but should be decomissioned so you can report on your hardware
turnover. However the following pages have delete functions photos, invoices

=item The list of models in the froddo addition page is restricted to only the
list of models used bby the frodo project currently, 3750, 3560, 224, 2960,
4948.
